name: Ansible Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show secret
        run: |
          echo "${{secrets.SSH_PRIVATE_KEY}}"
      - name: Install
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update
          sudo apt install ansible
          ansible-playbook --version

      - name: Version
        run: |
          ansible-playbook -h
